// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSpsXZZhC1-0N-z0Ue22mdHB3dXaISTYs',
    appId: '1:556086094033:web:bbf044fb3a1bf6839abdf0',
    messagingSenderId: '556086094033',
    projectId: 'flutter-186e5',
    authDomain: 'flutter-186e5.firebaseapp.com',
    storageBucket: 'flutter-186e5.appspot.com',
    measurementId: 'G-BR8QM841JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgFjq_WeMlZCrZIPoHkVewUOTc5ixGXZo',
    appId: '1:556086094033:android:266870b559eca6a09abdf0',
    messagingSenderId: '556086094033',
    projectId: 'flutter-186e5',
    storageBucket: 'flutter-186e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjVtgmL0Qr2HWRWarXZ_W0af8U_8Y3IPE',
    appId: '1:556086094033:ios:824cf72e95f6697d9abdf0',
    messagingSenderId: '556086094033',
    projectId: 'flutter-186e5',
    storageBucket: 'flutter-186e5.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjVtgmL0Qr2HWRWarXZ_W0af8U_8Y3IPE',
    appId: '1:556086094033:ios:fc8933119a99e4509abdf0',
    messagingSenderId: '556086094033',
    projectId: 'flutter-186e5',
    storageBucket: 'flutter-186e5.appspot.com',
    iosBundleId: 'com.example.firebaseDemo.RunnerTests',
  );
}
